---
title: "Recommendation System Draft"
author: "Pegasus"
output:
  html_document:
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
  pdf_document:
    latex_engine: xelatex
---
# Introduction 
## Definition:
Recommender Systems (RSs) are software  tools and techniques that provide users with suggestions for items that a user may wish to utilize.

## Purpose:
The purpose of RSs is to **assist** consumers to find what they indeed want easily.

## Functions: 
From where we stand, RS should have mainly the following fucntions:

(@) Increase the number of items sold
(@) Sell more diverse items
(@) Increase the users' satisfication
(@) Increase user fidelity
(@) Better understanding of what the user wants.


## Image:
The image of our RS should be build as **trustworthiness**. At begining, attention is should be taken into consideration. But in the long run, trustworthiness is the key point.  RS's image is to convince users to buy items. 
The are some rules for building RS:

+ Matthew Effect: the strong will be stronger.
+ Long tail theory: unpopular items together will have a big weight maybe even bigger than the top N popular items. 

## Constructure:
A Recommender system should have the following parts:

1. a complete index system:
2. a diversified recommendation algorithm system:
3. an effective test system
4. a specific feedback sytem

Also, RSs can be seen as the proceeding three parts: 

1. foreground display interface
    + place to displace
    + recommendation'results' title, thumbnail,and other content
    + average rating
    + reason for recommendation
2. background log system(database) 
3. recommendation algorithm system.

### Index System

RS is an information processing sytems that actively gather various kinds of data.But any data required can be sorted into three kinds of objects: **items**, **users** and **transaction**. as different techniques need different data input, To build a complete and canonical index system is second to none  for starting to build a RS.

1. **Items**:  Items are the objects that are waiting to be recommended.

    + genre (brand, function,step): 
    + SKU
    + price
    + volume
    + (price / volume)
    + *consumption rate
    + sales volume
    + *components
    + trend
2. **Users**: Users of an RS may have very diverse goals and characteristics.

    + User_id
    + location
    + *age
    + profession
    + education

3. **Transaction**: We generically referto a transanction as a recoreded interaction between a user and the RS.

    + order
    + rating
    + context: time( day, week, month,season)
    + comment
    + log-like data

Making a complete and canonical index system is the first step to build a recommender system, which decides its most important position. we should  take this part seriously.

### Recommendation Algorithm System
A RS must **predict** that an item is worth recommending. In order to do this, the system must be able to predict sthe utility of some itemws, or at least compare the utility of some items. and then decider which items to recommend based on this comparison.The prediction step may not be explicit in the recommendation algorithm but we can still apply this unifying model to describe the general role of an RS. 
Recommender System's core function is to predict which item(s) worthwell to recommend for target user(s).And this is directly determined by the algorithm System. The core of the RS is it's algorithms, and the core of the algorithms is the **similarity**. There is a implicit assumption that the items users utilize is the most useful, and the more similarity of another item(s) with them, the more useful the item(s) is(are). All the algorithms are created around the attribute. And differet ways to measure similarity generate different algorithms: 

There are four way to make recommendation engines(REs):

     + Personalized recommendation – recommend things based on the individual’s past behavior
     + Social recommendation – recommend things based on the past behavior of similar users
     + Item recommendation – recommend things based on the item itself
     + A combination of the three approaches above
 according different way of making REs, we have the following classes of recommendation algorithms:
 
 1. **Content-based**: The engines learns to recommend items that are similar to the ones that the user liked in the past. The similarity of items is calculated based on the features associated with the compared items. The items' attributes are simply keywords that are extracted from the items' descriptions. Semantic indexing techniques represent the item and user profiles using concepts intead of keywords.

2. **Collaborative Filtering(CF)** as its name indicates,collaborative filtering could filter users' uniterested items then recommend a recommendation list via constantly interactive of all users. There are three main branches of CF

    + neighborhood-based method
        + user-based collabrative filtering method(UCF)
        + item-based collabrative filtering method(ICF)
    + latent factor model
    + random walk on graph

3. **Demographic** this type of engines recommends items based on the demographic profile of the user.

4. **Knowledge-Based** Knowledge-based systems recommend items based on specific domain knowledge about how certain item features meet users' needs and preferences and, ultimately, how the item is useful for the user.

    + Case-based
    + Constrained-based: both systems are similar,user requirements are collected, repairs for inconsistent requirements are automatically proposed in situations wherer no solution could be found. The major difference lies in the way solutions are calculated. case-based recommenders determine recommendations on the basis of similarity metrics whereas constraint-based recommenders predominantly exploit predefined knowledge bases taht contain explicit rules about how to relate customer requirements with item features.
    + Community-based: based on the preferences of the user's friends. Evidence suggests that people tend to rely more on recommendation from their friends than on recommendations from similar but anonymous individuals.    
5. **Hybrid Recommender Systems** the combination fo the above mentioned techniques.

## Recommender System Evaluation: 
The necessity of evaluating the quality and value of the systems is undoubt, Evaluation is required at different stages of the system's life cycle and for various purposes.
1. off-line experiment

2. user study(survey)

3. online experiment(A/B test)















































### 1. Recommendation for normal customers
  + 1. method: Collaborative Filter
  + clustering : k-means
  + indexes used: user_id; rating or (num of each product bought by every customers) or other...; prodcuts_id; a history of every customers
  + description: collaborative filter is a way to use people's rating for recommendation, i.e., we make use of the masses' intellegence. And the filter has the capability of self-learning.


  + 2. method: content filter
  + 
  + description: content filter is to recommend depending on similiarty of products
  
## Make use of customers' behavior data
customer behavior data
customer behaviors : explicit feedback and immplict feedback
explicit feedback: include clear customers' tastes: rating sytems: like/dislike five star rating
explicit feedback: classic implicit feedback behavior: browsing behavior.

PS: period for stay could be a explict feedback customer behviors

  info|explict feedback| implicit feedback
------|----------------|------------
users' tastes| clear   | not clear
scale | small         | large
feedback type| both | only positive

Customers' behavior general expression (index)
user_id
item_id
behavior type : buy or just browse
context: time, location should be included
behavior weight:
behavior content: label, rating, etc.

### Analysis for data behavior

#### Collaborative Filtering



##### neighborhood-based method


######  user-based collaborative filtering
Drawbacks: the more users the more complicated it is, i.e., time consuming and space consuming sharply. 
###### item-based collaborative filtering 
+ step 1: calculate similarity between items
+ step 2: according to similarity and behavior history, RS generate recommendation list for user.
key point is how to measure similarity, the following is a popular similarity:
$$\omega_{ij} = \frac{|N(i)\cap N(j)|}{\sqrt{|N(i)||N(j)|}} $$
Where $|N(i)|$ is the number of users who like item i.


Drawbacks of CF: hot sales have high similarity.

## Latent Factor model (LFM)

LFM measure user u's interest to item i:
$$ Preference(\mu,i) = r_{\mu i} = p_{u}^T q_i = \sum_{f = 1}^{F} p_{u,k}q_{i,k}$$
Where $p_{u,k}$ measure the relation between user u's interest and kth latent class, and $q_{i,k}$ measure teh relation between kth latent class and item i. LFM work well on explicit feedback data. to implicit data, we should generate negative samples for every users. 
Negative samples should 1: have a similar size with positive examples; 2: to choose  hot sales that customers didn't show interest.

After samples, we could get a user-item set $K = \{(\mu,\nu)\}$, if $(\mu,i)$ is positive, then $_{\mu i} = 1$, else $r_{\mu i} = 0$. After this, we should optimize the following equation to get proper p and q:
$$C = \sum_{(\mu,i)\in K}\bigg(r_{\mu i} - \sum_{k =1}^{K}p_{\mu,k}q_{i,k}\bigg)^2 + \lambda(||p_{\mu}||^2 +||q_i||^2) $$
where $\lambda(||p_{\mu}||^2 +||q_i||^2) $ is used to avoid overfitting, $\lambda$ could get by experiment.

LFM hardly give recommendation constantly.

### Graph-based 










## Recommendation for the new
  + method: sorting algorithm
  + indexes used: volume of every prodcuts
  

# RS test

## 1 off-line experiment

## 2 user study

## 3 online experiment

ABtest

estimate index

+ consumer satisfication degree
+ predicted accuracy
+ 